// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from 'react'

export const Index: Record<string, any> = {
  default: {
    accordion: {
      name: 'accordion',
      type: 'components:ui',
      registryDependencies: undefined,
      component: React.lazy(() => import('@/components/ui/accordion')),
      files: ['components/ui/accordion'],
      category: 'undefined',
      subcategory: 'undefined',
    },
  },
}
